Repository ae-utbm/sith3, pull requests merged in 2023-05, with the labels that each got.

#634 Better usage of cache for groups and clubs related operations
  accounting/models.py
  accounting/templates/accounting/bank_account_details.jinja
  accounting/templates/accounting/bank_account_list.jinja
  accounting/templates/accounting/club_account_details.jinja
  accounting/templates/accounting/co_list.jinja
  accounting/templates/accounting/journal_details.jinja
  accounting/templates/accounting/label_list.jinja
  accounting/views.py
  club/forms.py
  club/models.py
  club/templates/club/club_members.jinja
  club/tests.py
  club/views.py
  com/models.py
  com/templates/com/news_detail.jinja
  com/templates/com/news_edit.jinja
  com/templates/com/news_list.jinja
  com/tests.py
  com/views.py
  core/apps.py
  core/management/commands/populate.py
  core/models.py
  core/signals.py
  core/templates/core/file_detail.jinja
  core/templates/core/user_clubs.jinja
  core/templates/core/user_detail.jinja
  core/templates/core/user_edit.jinja
  core/templates/core/user_tools.jinja
  core/tests.py
  core/views/user.py
  counter/models.py
  counter/views.py
  doc/TW_Skia/Rapport.tex
  election/models.py
  election/views.py
  forum/models.py
  forum/templates/forum/forum.jinja
  forum/templates/forum/main.jinja
  launderette/models.py
  launderette/templates/launderette/launderette_book_choose.jinja
  launderette/templates/launderette/launderette_main.jinja
  pedagogy/models.py
  pedagogy/tests.py
  sas/models.py
  sas/templates/sas/album.jinja
  sas/templates/sas/main.jinja
  sas/views.py
  sith/settings.py
  stock/models.py
  subscription/models.py
Labels: b: optimisations, backend

#628 Galaxy improvements
  .gitignore
  core/management/commands/populate.py
  galaxy/management/commands/generate_galaxy_test_data.py
  galaxy/management/commands/rule_galaxy.py
  galaxy/migrations/0002_auto_20230412_1130.py
  galaxy/models.py
  galaxy/ref_galaxy_state.json
  galaxy/templates/galaxy/user.jinja
  galaxy/tests.py
  galaxy/views.py
Labels: backend, frontend

#647 [FIX] Fix cached groups
  core/models.py
  core/tests.py
Labels: b: core, backend
